import type { Course, Track } from "./types";

const SECURITY: Track = "Computer Security";
const SYSTEMS: Track = "Computer and Software Systems";
const SOFTWARE: Track = "Software Engineering & Information Management";
const AI: Track = "Artificial Intelligence & Cognitive Science";
const GRAPHICS: Track = "Graphics & Vision";
const THEORY: Track = "Computing Concepts & Themes";

export const courses: Course[] = [
  { id:"CS110", code:"01:198:110", short:"CS110", title:"Principles of Computer Science", credits:3, group:"transition", csDept:true, level:100, description:"General CS course. Does not count as a CS major core course." },
  { id:"CS111", code:"01:198:111", short:"CS111", title:"Introduction to Computer Science", credits:4, group:"core", csDept:true, level:100, description:"Legacy introductory CS course for continuing students. Official prerequisite is MATH115 or placement into Calculus I; that placement detail is not modeled here.", prereqsVerified:false },
  { id:"CS112", code:"01:198:112", short:"CS112", title:"Data Structures", credits:4, group:"core", csDept:true, level:100, description:"Legacy data structures course.", prereqGroups:[["CS111","CS121"]], prereqsVerified:true },
  { id:"CS120", code:"01:198:120", short:"CS120", title:"Introduction to Programming", credits:4, group:"transition", csDept:true, level:100, description:"New introductory course beginning with the 2027 transition. Does not earn CS major credit." },
  { id:"CS121", code:"01:198:121", short:"CS121", title:"Introduction to Computer Science", credits:4, group:"core", csDept:true, level:100, description:"New introductory CS major course.", prereqGroups:[["CS120"]], prereqsVerified:true },
  { id:"CS122", code:"01:198:122", short:"CS122", title:"Data Structures", credits:4, group:"core", csDept:true, level:100, description:"New data structures course replacing CS112 for the new sequence.", prereqGroups:[["CS121","CS111"]], prereqsVerified:true },
  { id:"CS205", code:"01:198:205", short:"CS205", title:"Introduction to Discrete Structures I", credits:4, group:"core", csDept:true, level:200, description:"Logic, sets, relations, functions, induction, and proofs.", prereqGroups:[["CS111","CS121"],["MATH151"]], prereqsVerified:true },
  { id:"CS206", code:"01:198:206", short:"CS206", title:"Introduction to Discrete Structures II", credits:4, group:"core", csDept:true, level:200, description:"Counting, discrete probability, recurrence relations, and graph theory.", prereqGroups:[["CS205"]], prereqsVerified:true },
  { id:"CS211", code:"01:198:211", short:"CS211", title:"Computer Architecture", credits:4, group:"core", csDept:true, level:200, description:"Computer organization and the hardware/software interface.", prereqGroups:[["CS112","CS122"]], prereqsVerified:true },
  { id:"CS344", code:"01:198:344", short:"CS344", title:"Design and Analysis of Computer Algorithms", credits:4, group:"core", csDept:true, level:300, description:"Algorithm design and analysis.", prereqGroups:[["CS112","CS122"],["CS206"]], prereqsVerified:true },

  { id:"MATH151", code:"01:640:151", short:"MATH151", title:"Calculus I for Math and Physical Sciences", credits:4, group:"math", csDept:false, level:100 },
  { id:"MATH152", code:"01:640:152", short:"MATH152", title:"Calculus II for Math and Physical Sciences", credits:4, group:"math", csDept:false, level:100, prereqGroups:[["MATH151"]], prereqsVerified:true },
  { id:"MATH250", code:"01:640:250", short:"MATH250", title:"Introductory Linear Algebra", credits:3, group:"math", csDept:false, level:200 },

  { id:"CS210", code:"01:198:210", short:"CS210", title:"Data Management for Data Science", group:"cs-elective", csDept:true, level:200, designatedElective:true, tracks:[SOFTWARE] },
  { id:"CS213", code:"01:198:213", short:"CS213", title:"Software Methodology", group:"cs-elective", csDept:true, level:200, designatedElective:true, tracks:[SYSTEMS,SOFTWARE] },
  { id:"CS214", code:"01:198:214", short:"CS214", title:"Systems Programming", group:"cs-elective", csDept:true, level:200, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE,GRAPHICS] },
  { id:"CS314", code:"01:198:314", short:"CS314", title:"Principles of Programming Languages", group:"cs-elective", csDept:true, level:300, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE,AI,THEORY] },
  { id:"CS323", code:"01:198:323", short:"CS323", title:"Numerical Analysis and Computing", group:"cs-elective", csDept:true, level:300, designatedElective:true, tracks:[GRAPHICS,THEORY] },
  { id:"CS324", code:"01:198:324", short:"CS324", title:"Numerical Methods", group:"cs-elective", csDept:true, level:300, designatedElective:true },
  { id:"CS334", code:"01:198:334", short:"CS334", title:"Introduction to Imaging and Multimedia", group:"cs-elective", csDept:true, level:300, designatedElective:true, tracks:[GRAPHICS,THEORY] },
  { id:"CS336", code:"01:198:336", short:"CS336", title:"Principles of Information and Data Management", group:"cs-elective", csDept:true, level:300, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE,AI,THEORY] },
  { id:"CS352", code:"01:198:352", short:"CS352", title:"Internet Technology", group:"cs-elective", csDept:true, level:300, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE,THEORY] },
  { id:"CS411", code:"01:198:411", short:"CS411", title:"Computer Architecture II", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS] },
  { id:"CS415", code:"01:198:415", short:"CS415", title:"Compilers", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE] },
  { id:"CS416", code:"01:198:416", short:"CS416", title:"Operating Systems Design", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE] },
  { id:"CS417", code:"01:198:417", short:"CS417", title:"Distributed Systems: Concepts and Design", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE] },
  { id:"CS419", code:"01:198:419", short:"CS419", title:"Computer Security", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE] },
  { id:"CS424", code:"01:198:424", short:"CS424", title:"Modeling and Simulation of Continuous Systems", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS425", code:"01:198:425", short:"CS425", title:"Brain-Inspired Computing", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS428", code:"01:198:428", short:"CS428", title:"Introduction to Computer Graphics", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[GRAPHICS] },
  { id:"CS431", code:"01:198:431", short:"CS431", title:"Software Engineering", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SOFTWARE] },
  { id:"CS437", code:"01:198:437", short:"CS437", title:"Database Systems Implementation", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,SYSTEMS,SOFTWARE] },
  { id:"CS439", code:"01:198:439", short:"CS439", title:"Introduction to Data Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS440", code:"01:198:440", short:"CS440", title:"Introduction to Artificial Intelligence", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[AI,THEORY] },
  { id:"CS442", code:"01:198:442", short:"CS442", title:"Topics in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS443", code:"01:198:443", short:"CS443", title:"Topics in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS444", code:"01:198:444", short:"CS444", title:"Topics in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS445", code:"01:198:445", short:"CS445", title:"Topics in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS452", code:"01:198:452", short:"CS452", title:"Formal Languages and Automata", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[SECURITY,THEORY] },
  { id:"CS460", code:"01:198:460", short:"CS460", title:"Introduction to Computational Robotics", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS461", code:"01:198:461", short:"CS461", title:"Machine Learning Principles", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[AI] },
  { id:"CS462", code:"01:198:462", short:"CS462", title:"Introduction to Deep Learning", group:"cs-elective", csDept:true, level:400, designatedElective:true, tracks:[AI] },
  { id:"CS493", code:"01:198:493", short:"CS493", title:"Independent Study in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },
  { id:"CS494", code:"01:198:494", short:"CS494", title:"Independent Study in Computer Science", group:"cs-elective", csDept:true, level:400, designatedElective:true },

  { id:"ECE376", code:"14:332:376", short:"ECE376", title:"Virtual Reality", group:"related-elective", csDept:false, level:300, designatedElective:true },
  { id:"ECE423", code:"14:332:423", short:"ECE423", title:"Telecommunication Networks", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE424", code:"14:332:424", short:"ECE424", title:"Introduction to Information and Network Security", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[SECURITY] },
  { id:"ECE443", code:"14:332:443", short:"ECE443", title:"Machine Learning for Engineers", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE451", code:"14:332:451", short:"ECE451", title:"Introduction to Parallel and Distributed Computing", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE452", code:"14:332:452", short:"ECE452", title:"Software Engineering", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE453", code:"14:332:453", short:"ECE453", title:"Mobile App Engineering and User Experience", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE456", code:"14:332:456", short:"ECE456", title:"Network-Centric Programming", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"ECE472", code:"14:332:472", short:"ECE472", title:"Robotics and Computer Vision", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"MATH338", code:"01:640:338", short:"MATH338", title:"Discrete and Probabilistic Models in Biology", group:"related-elective", csDept:false, level:300, designatedElective:true },
  { id:"MATH348", code:"01:640:348", short:"MATH348", title:"Cryptography", group:"related-elective", csDept:false, level:300, designatedElective:true, tracks:[SECURITY] },
  { id:"MATH354", code:"01:640:354", short:"MATH354", title:"Linear Optimization", group:"related-elective", csDept:false, level:300, designatedElective:true },
  { id:"MATH428", code:"01:640:428", short:"MATH428", title:"Graph Theory", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"MATH454", code:"01:640:454", short:"MATH454", title:"Combinatorial Theory", group:"related-elective", csDept:false, level:400, designatedElective:true },
  { id:"MATH461", code:"01:640:461", short:"MATH461", title:"Mathematical Logic and Foundations of Mathematics", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"PHIL315", code:"01:730:315", short:"PHIL315", title:"Applied Symbolic Logic", group:"related-elective", csDept:false, level:300, designatedElective:true, tracks:[AI] },
  { id:"PHIL407", code:"01:730:407", short:"PHIL407", title:"Intermediate Logic I", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"PHIL408", code:"01:730:408", short:"PHIL408", title:"Intermediate Logic II", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"PHIL329", code:"01:730:329", short:"PHIL329", title:"Minds, Machines, & Persons", group:"related-elective", csDept:false, level:300, designatedElective:true, tracks:[AI] },
  { id:"PHIL424", code:"01:730:424", short:"PHIL424", title:"The Logic of Decision", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"LING441", code:"01:615:441", short:"LING441", title:"Linguistics and Cognitive Science", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"STAT384", code:"01:960:384", short:"STAT384", title:"Intermediate Statistical Analysis", group:"related-elective", csDept:false, level:300, designatedElective:true, tracks:[AI] },
  { id:"STAT463", code:"01:960:463", short:"STAT463", title:"Regression Methods", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"STAT476", code:"01:960:476", short:"STAT476", title:"Introduction to Sampling", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },
  { id:"STAT486", code:"01:960:486", short:"STAT486", title:"Computing and Graphics in Applied Statistics", group:"related-elective", csDept:false, level:400, designatedElective:true, tracks:[AI] },

  { id:"PHYS203", code:"01:750:203", short:"PHYS203", title:"General Physics I", group:"science", csDept:false },
  { id:"PHYS204", code:"01:750:204", short:"PHYS204", title:"General Physics II", group:"science", csDept:false },
  { id:"PHYS205", code:"01:750:205", short:"PHYS205", title:"General Physics Lab I", group:"science", csDept:false },
  { id:"PHYS206", code:"01:750:206", short:"PHYS206", title:"General Physics Lab II", group:"science", csDept:false },
  { id:"PHYS123", code:"01:750:123", short:"PHYS123", title:"Analytical Physics I-A", group:"science", csDept:false },
  { id:"PHYS124", code:"01:750:124", short:"PHYS124", title:"Analytical Physics I-B", group:"science", csDept:false },
  { id:"PHYS227", code:"01:750:227", short:"PHYS227", title:"Analytical Physics II-A", group:"science", csDept:false },
  { id:"PHYS229", code:"01:750:229", short:"PHYS229", title:"Analytical Physics II-B", group:"science", csDept:false },
  { id:"PHYS271", code:"01:750:271", short:"PHYS271", title:"Honors Physics I", group:"science", csDept:false },
  { id:"PHYS272", code:"01:750:272", short:"PHYS272", title:"Honors Physics II", group:"science", csDept:false },
  { id:"PHYS275", code:"01:750:275", short:"PHYS275", title:"Honors Physics Lab I", group:"science", csDept:false },
  { id:"PHYS276", code:"01:750:276", short:"PHYS276", title:"Honors Physics Lab II", group:"science", csDept:false },
  { id:"PHYS201", code:"01:750:201", short:"PHYS201", title:"Extended General Physics I", group:"science", csDept:false },
  { id:"PHYS202", code:"01:750:202", short:"PHYS202", title:"Extended General Physics II", group:"science", csDept:false },
  { id:"PHYS193", code:"01:750:193", short:"PHYS193", title:"Physics Sequence Course I", group:"science", csDept:false },
  { id:"PHYS194", code:"01:750:194", short:"PHYS194", title:"Physics Sequence Course II", group:"science", csDept:false },
  { id:"CHEM159", code:"01:160:159", short:"CHEM159", title:"General Chemistry for Engineers I", group:"science", csDept:false },
  { id:"CHEM160", code:"01:160:160", short:"CHEM160", title:"General Chemistry for Engineers II", group:"science", csDept:false },
  { id:"CHEM161", code:"01:160:161", short:"CHEM161", title:"General Chemistry", group:"science", csDept:false },
  { id:"CHEM162", code:"01:160:162", short:"CHEM162", title:"General Chemistry II", group:"science", csDept:false },
  { id:"CHEM163", code:"01:160:163", short:"CHEM163", title:"Honors General Chemistry I", group:"science", csDept:false },
  { id:"CHEM164", code:"01:160:164", short:"CHEM164", title:"Honors General Chemistry II", group:"science", csDept:false },
  { id:"CHEM171", code:"01:160:171", short:"CHEM171", title:"Introduction to Experimentation", group:"science", csDept:false },
];

export const scienceSequences = [
  ["PHYS203","PHYS204","PHYS205","PHYS206"],
  ["PHYS123","PHYS124","PHYS227","PHYS229"],
  ["PHYS271","PHYS272","PHYS275","PHYS276"],
  ["PHYS201","PHYS202"],
  ["PHYS193","PHYS194"],
  ["CHEM159","CHEM160","CHEM171"],
  ["CHEM161","CHEM162","CHEM171"],
  ["CHEM163","CHEM164","CHEM171"],
];

export const trackOptions: Track[] = [
  "None",
  "Computer Security",
  "Computer and Software Systems",
  "Software Engineering & Information Management",
  "Artificial Intelligence & Cognitive Science",
  "Graphics & Vision",
  "Computing Concepts & Themes",
];
